name: Test AWS Credentials

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select deploy environment'
        required: true
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAZ2Y6FLTRDNY4J3UT
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Test AWS credentials
        run: |
          aws sts get-caller-identity
